# Hypraway v1.1 configuration file
check_interval: 5

# Enable notifications for power state changes
enable_notifications: true

# AC power mode
ac_path: "/sys/class/power_supply/ADP1/online"
battery_path: "/sys/class/power_supply/BAT1/status"

ac:
  # Level 1: Notify user away
  level1:
    timeout: 600  # 10 minutes
    command: "gtklock"
  # Level 2: Lock screen
  level2:
    timeout:  1200 # 20 minutes
    command: "systemctl suspend"
  # Level 3: Suspend or Hibernate
  level3:
    timeout: 0 # disabled
    command: "systemctl hibernate"

# Battery mode
battery:
  # Level 1: Notify user away
  level1:
    timeout: 300  # 5 minutes
    command: "gtklock"
  # Level 2: Lock screen
  level2:
    timeout: 600  # 10 minutes
    command: "systemctl suspend"
  # Level 3: Suspend or Hibernate
  level3:
    timeout: 900  # 15 minutes
    command: "systemctl hibernate"
